### ISSUE TITLE
Game Menu Mod Option crashes server

### ISSUE THREAD

**Issue by Akaitatsu** [MORIMORI0317/GameMenuModOption#5]
If included in mods on a 1.15.2 dedicated server, this mod crashes during the startup sequence. If left out and on client side only it shows mod incompatibility, though you can still join a server.

Excerpt of crash log.

```
Caused by: net.minecraftforge.fml.ModLoadingException: Game Menu Mod Option has class loading errors
§7Attempted to load class net/minecraft/client/gui/widget/Widget for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:77) ~[?:31.2] {re:classloading}
	at sun.reflect.GeneratedConstructorAccessor36.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_265] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_265] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
	... 24 more
```

Full log: [crash-2020-10-16_16.43.14-server.txt](https://github.com/MORIMORI0317/GameMenuModOption/files/5396111/crash-2020-10-16_16.43.14-server.txt)

**Comment by nanonestor** [comment]
+1  --- Client side mods can be set so that they don't show incompatibility / server mod list mis-match.  I just worked with the author of the Horse Stats mod - [https://www.curseforge.com/minecraft/mc-mods/horse-statistics](url) to fix this same issue with his mod.  He successfully changed the mod code so that client side mod is not counted in mod list matchup.

I'd like to include this mod with my modpack but I will not do so until this issue is resolved.
