### ISSUE TITLE
Crash when opening in-world game menu after latest patch

### ISSUE THREAD

**Issue by arademacker** [MORIMORI0317/GameMenuModOption#8]
Minecraft Version _1.16.5_
Forge Version _forge-36.1.1_
GameMenuModOption Version _1.16.4-1.6_
Java Version _1.8.0_51_
Custom Modpack via Curseforge Launcher through Overwolf
Running Optifine, RandomPatches and your other mod GameMenuRemoveGFARB,
though I don't think any of them caused this. RandomPatches hooks into keybindings including `Esc` but otherwise does not touch the menu. Neither does Optifine. This mod was the last and only mod to update before the crash.

Was able to reproduce the bug reliably by
* Opening game
* Loading world
* Pressing `Esc` to open menu
Timing seems to be irrelevant. Pressing Esc immediately as well as some minutes after world load has the same result with the same error message. Removing this mod prevented the error from happening.

The world saves just fine before the menu opens, thankfully. I can provide more info or experiment some more if you need anything else.

Full log files here, I copied out the actual error that leads to the crash below.
[2021-03-31-1.log](https://github.com/MORIMORI0317/GameMenuModOption/files/6236267/2021-03-31-1.log)
[2021-03-31-2.log](https://github.com/MORIMORI0317/GameMenuModOption/files/6236268/2021-03-31-2.log)

```
java.lang.IndexOutOfBoundsException: Index: 7, Size: 6
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
	at net.morimori.gamemenumodoption.GuiHandler.onGUI(GuiHandler.java:19)
	at net.minecraftforge.eventbus.ASMEventHandler_2411_GuiHandler_onGUI_Post.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2612/514611129.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraft.client.gui.screen.Screen.func_231158_b_(Screen.java:327)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:852)
	at net.minecraft.client.Minecraft.func_71385_j(Minecraft.java:1250)
	at com.therandomlabs.randompatches.client.RPKeyBindingHandler$KeyBindings.onKeyEvent(RPKeyBindingHandler.java:127)
	at net.minecraft.client.KeyboardListener.handler$zbo000$onKeyEvent(KeyboardListener.java:781)
	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:421)
	at net.minecraft.client.KeyboardListener.lambda$null$7(KeyboardListener.java:622)
	at net.minecraft.client.KeyboardListener$$Lambda$28958/765843488.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:106)
	at net.minecraft.client.KeyboardListener.lambda$setupCallbacks$8(KeyboardListener.java:621)
	at net.minecraft.client.KeyboardListener$$Lambda$2911/1433035552.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallback$Container.invoke(GLFWKeyCallback.java:82)
	at tschipp.carryon.common.helper.KeyboardCallbackWrapper.keyCallback(KeyboardCallbackWrapper.java:29)
	at tschipp.carryon.common.helper.KeyboardCallbackWrapper$$Lambda$21358/1793962612.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102)
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:398)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$484/1817415346.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption/files/3256467
https://www.curseforge.com/minecraft/mc-mods/game-menu-remove-gfarb/files/3256464
Please update "Game Menu Remove GFARB" and "Game Menu Mod Option" to the latest version

**Comment by arademacker** [comment]
Works flawlessly, thank you very much.
